apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
spec:
  selector:
    app: weather-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # AWS Load Balancer'ı otomatik açar!
